version: "2"
services:

  web:
    build: app/
    volumes:
      - ./app/:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  db:
    build: database/
    environment:
      POSTGRES_PASSWORD: puikula
